[tool.poetry]
name = "python-cpidr"
version = "0.1.0"
description = ""
authors = ["Jason Robison <jrrobison1@hoodsen.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
